spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fooda?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "!5dhtmdcks"
  resources:
    add-mappings: true

  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    open-in-view: false
    generate-ddl: true
#    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379

# TODO: location 경로 바꼈으므로 수정 요망
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: 12345678901234567890123456789012

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

